"""empty message

Revision ID: 952b8f3933ad
Revises: 
Create Date: 2019-12-11 12:34:44.646933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952b8f3933ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phoneNumber', sa.String(length=11), nullable=False),
    sa.Column('photoUrl', sa.String(), nullable=True),
    sa.Column('verifiedEmail', sa.Boolean(), nullable=True),
    sa.Column('verifiedPhone', sa.Boolean(), nullable=True),
    sa.Column('passwordHash', sa.String(length=128), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photoUrl')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phoneNumber'), 'users', ['phoneNumber'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phoneNumber'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
